---
title: "Import dengue, zika, chikungunya events from SIM and SINAN"
format: html
---

## Packages

```{r}
#| message: false
library(dplyr)
library(readr)
library(lubridate)
library(RPostgres)
library(DBI)
library(brpop)
library(sessioninfo)
```

## Database connection

```{r}
con <- dbConnect(
  drv = Postgres(),
  host = Sys.getenv("psql_local_host"),
  dbname = Sys.getenv("psql_db"),
  user = Sys.getenv("psql_local_user"),
  password = Sys.getenv("psql_local_psw")
)

schema <- Sys.getenv("psql_schema")
```

## Data import

```{r}
cases_file <- "../dados/tb_deng_chagas_zik_chko.csv"
```

```{r}
tmp <- read_csv2(file = cases_file) |>
  mutate(
    sex = case_match(
      sex,
      "M" ~ "1",
      "F" ~ "2",
      "I" ~ "0",
      .default = sex
    )
  ) |>
  mutate(
    geocod = as.numeric(geocod),
    year = as.numeric(year),
    month = as.numeric(month),
    epiweek = as.numeric(epiweek),
    date = as.Date(date),
    health = as.character(health),
    sex = as.numeric(sex),
    age = as.numeric(age),
    source = as.character(source)
  )
```

## Add geo codes

Add UF and health regions.

```{r}
tmp <- tmp |>
  rename(geocodmu = geocod) |>
  mutate(geocoduf = as.numeric(substr(geocodmu, 0, 2))) |>
  left_join(mun_reg_saude_449, by = c("geocodmu" = "code_muni")) |>
  rename(geocodrs = codi_reg_saude) |>
  relocate(c(geocoduf, geocodrs), .before = geocodmu)
```

## Write data

### Dengue (SIM)

```{r}
if (dbExistsTable(con, Id(schema = schema, table = "dengue_sim"))) {
  dbRemoveTable(con, Id(schema = schema, table = "dengue_sim"))
}

dbWriteTable(
  conn = con,
  name = Id(schema = schema, table = "dengue_sim"),
  value = tmp |>
    filter(health == "Dengue", source == "SIM") |>
    select(-health, -source)
)
```

### Dengue (SINAN)

```{r}
if (dbExistsTable(con, Id(schema = schema, table = "dengue_sinan"))) {
  dbRemoveTable(con, Id(schema = schema, table = "dengue_sinan"))
}

dbWriteTable(
  conn = con,
  name = Id(schema = schema, table = "dengue_sinan"),
  value = tmp |>
    filter(health == "Dengue", source == "SINAN") |>
    select(-health, -source)
)
```

### Zika (SINAN)

```{r}
if (dbExistsTable(con, Id(schema = schema, table = "zika_sinan"))) {
  dbRemoveTable(con, Id(schema = schema, table = "zika_sinan"))
}

dbWriteTable(
  conn = con,
  name = Id(schema = schema, table = "zika_sinan"),
  value = tmp |>
    filter(health == "Zika", source == "SINAN") |>
    select(-health, -source)
)
```

### Chikungunya (SINAN)

```{r}
if (dbExistsTable(con, Id(schema = schema, table = "chikungunya_sinan"))) {
  dbRemoveTable(con, Id(schema = schema, table = "chikungunya_sinan"))
}

dbWriteTable(
  conn = con,
  name = Id(schema = schema, table = "chikungunya_sinan"),
  value = tmp |>
    filter(health == "Chikungunya", source == "SINAN") |>
    select(-health, -source)
)
```

### Chagas (SINAN)

```{r}
if (dbExistsTable(con, Id(schema = schema, table = "chagas_sinan"))) {
  dbRemoveTable(con, Id(schema = schema, table = "chagas_sinan"))
}

dbWriteTable(
  conn = con,
  name = Id(schema = schema, table = "chagas_sinan"),
  value = tmp |>
    filter(health == "Chagas", source == "SINAN") |>
    select(-health, -source)
)
```

## Tables conference

```{r}
dbListTables(con)
```

## Database disconnect

```{r}
dbDisconnect(con)
```

## Session info

```{r}
session_info()
```
