---
title: "Harmonize indicators"
format:
  html:
    embed-resources: true
---

## Packages

```{r}
#| message: false
library(dplyr)
library(lubridate)
library(RPostgres)
library(DBI)
library(brindi)
library(ggplot2)
library(arrow)
library(sessioninfo)
```

## Dengue mortality

```{r}
indi_0014_res <- indi_0014(
  agg = "mun_res",
  agg_time = "month",
  ano = 2000:2023,
  pop_source = "datasus2024",
  adjust_rates = FALSE
)
```

```{r}
indi_0014_res |>
  filter(cod == 330455) |>
  mutate(
    date = as.Date(paste0(substr(date, 0, 4), "-", substr(date, 6, 7), "-01"))
  ) |>
  ggplot(aes(x = date, y = value)) +
  geom_line() +
  labs(
    title = "Dengue mortality",
    subtitle = "Rio de Janeiro, RJ",
    caption = "per 100,000 inhab."
  )
```

## Dengue incidence

```{r}
indi_0015_res <- indi_0015(
  agg = "mun_res",
  agg_time = "month",
  ano = 2000:2023,
  pop_source = "datasus2024",
  adjust_rates = FALSE
)
```

```{r}
indi_0015_res |>
  filter(cod == 330455) |>
  mutate(
    date = as.Date(paste0(substr(date, 0, 4), "-", substr(date, 6, 7), "-01"))
  ) |>
  ggplot(aes(x = date, y = value)) +
  geom_line() +
  labs(
    title = "Dengue incidence",
    subtitle = "Rio de Janeiro, RJ",
    caption = "per 100,000 inhab."
  )
```

## Zika incidence

```{r}
indi_0016_res <- indi_0016(
  agg = "mun_res",
  agg_time = "month",
  ano = 2000:2023,
  pop_source = "datasus2024",
  adjust_rates = FALSE
)
```

```{r}
indi_0016_res |>
  filter(cod == 330455) |>
  mutate(
    date = as.Date(paste0(substr(date, 0, 4), "-", substr(date, 6, 7), "-01"))
  ) |>
  ggplot(aes(x = date, y = value)) +
  geom_line() +
  labs(
    title = "Zika incidence",
    subtitle = "Rio de Janeiro, RJ",
    caption = "per 100,000 inhab."
  )
```

## Chikungunya incidence

```{r}
indi_0017_res <- indi_0017(
  agg = "mun_res",
  agg_time = "month",
  ano = 2000:2023,
  pop_source = "datasus2024",
  adjust_rates = FALSE
)
```

```{r}
indi_0017_res |>
  filter(cod == 330455) |>
  mutate(
    date = as.Date(paste0(substr(date, 0, 4), "-", substr(date, 6, 7), "-01"))
  ) |>
  ggplot(aes(x = date, y = value)) +
  geom_line() +
  labs(
    title = "Chikungunya incidence",
    subtitle = "Rio de Janeiro, RJ",
    caption = "per 100,000 inhab."
  )
```

## Yellow fever incidence

```{r}
indi_0018_res <- indi_0018(
  agg = "mun_res",
  agg_time = "month",
  ano = 2000:2023,
  pop_source = "datasus2024",
  adjust_rates = FALSE
)
```

```{r}
indi_0018_res |>
  filter(cod == 330455) |>
  mutate(
    date = as.Date(paste0(substr(date, 0, 4), "-", substr(date, 6, 7), "-01"))
  ) |>
  ggplot(aes(x = date, y = value)) +
  geom_line() +
  labs(
    title = "Yellow fever incidence",
    subtitle = "Rio de Janeiro, RJ",
    caption = "per 100,000 inhab."
  )
```

## Chagas incidence

```{r}
indi_0019_res <- indi_0019(
  agg = "mun_res",
  agg_time = "month",
  ano = 2000:2023,
  pop_source = "datasus2024",
  adjust_rates = FALSE
)
```

```{r}
indi_0019_res |>
  filter(cod == 330455) |>
  mutate(
    date = as.Date(paste0(substr(date, 0, 4), "-", substr(date, 6, 7), "-01"))
  ) |>
  ggplot(aes(x = date, y = value)) +
  geom_line() +
  labs(
    title = "Chagas incidence",
    subtitle = "Rio de Janeiro, RJ",
    caption = "per 100,000 inhab."
  )
```

## Export files

```{r}
write_parquet(
  x = indi_0014_res,
  sink = "../indicadores/indi_0014_munres_month_20002023.parquet"
)

write_parquet(
  x = indi_0015_res,
  sink = "../indicadores/indi_0015_munres_month_20002023.parquet"
)

write_parquet(
  x = indi_0016_res,
  sink = "../indicadores/indi_0016_munres_month_20002023.parquet"
)

write_parquet(
  x = indi_0017_res,
  sink = "../indicadores/indi_0017_munres_month_20002023.parquet"
)

write_parquet(
  x = indi_0018_res,
  sink = "../indicadores/indi_0018_munres_month_20002023.parquet"
)

write_parquet(
  x = indi_0019_res,
  sink = "../indicadores/indi_0019_munres_month_20002023.parquet"
)
```

## Session info

```{r}
session_info()
```
